.TH "filenames.cpp" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filenames.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'filenames.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <boost/format.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBstripSuffix\fP (string s, string suf)"
.br
.ti -1c
.RI "string \fBgetLogFilename\fP (string net_file)"
.br
.ti -1c
.RI "string \fBgetWordsFilename\fP (string net_file)"
.br
.ti -1c
.RI "string \fBmakeNetFilename\fP (int hid1, int hid2, int seq)"
.br
.ti -1c
.RI "bool \fBfileExists\fP (string filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool fileExists (string filename)"
.PP
Definition at line 24 of file filenames.cpp.
.SS "string getLogFilename (string net_file)"
.PP
Definition at line 12 of file filenames.cpp.
.SS "string getWordsFilename (string net_file)"
.PP
Definition at line 16 of file filenames.cpp.
.SS "string makeNetFilename (int hid1, int hid2, int seq)"
.PP
Definition at line 20 of file filenames.cpp.
.SS "string stripSuffix (string s, string suf)"
.PP
Definition at line 6 of file filenames.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
