.TH "sort_score" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sort_score \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::pair< size_t, double > &left, const std::pair< size_t, double > &right)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file predict.cpp.
.SH "Member Function Documentation"
.PP 
.SS "bool sort_score::operator() (const std::pair< size_t, double > & left, const std::pair< size_t, double > & right)\fC [inline]\fP"
.PP
Definition at line 23 of file predict.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
