.TH "substwords.cpp" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
substwords.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmatchDigits\fP (string &s, size_t start=0, size_t end=0)"
.br
.ti -1c
.RI "bool \fBisNumber\fP (string &s)"
.br
.ti -1c
.RI "bool \fBisOrdinal\fP (string &s)"
.br
.ti -1c
.RI "string \fBperformSubstitutions\fP (string word)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool isNumber (string & s)"
.PP
Definition at line 12 of file substwords.cpp.
.SS "bool isOrdinal (string & s)"
.PP
Definition at line 16 of file substwords.cpp.
.SS "bool matchDigits (string & s, size_t start = \fC0\fP, size_t end = \fC0\fP)"
.PP
Definition at line 5 of file substwords.cpp.
.SS "string performSubstitutions (string word)"
.PP
Definition at line 28 of file substwords.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
