.TH "substwords.hpp" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
substwords.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBperformSubstitutions\fP (string word)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string performSubstitutions (string word)"
.PP
Definition at line 28 of file substwords.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
