.TH "wordstats.cpp" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wordstats.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include 'words.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP ()"
.br
.ti -1c
.RI "void \fBparseOptions\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 39 of file wordstats.cpp.
.SS "void parseOptions (int argc, char * argv[])"
.PP
Definition at line 15 of file wordstats.cpp.
.SS "void usage ()"
.PP
Definition at line 8 of file wordstats.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
