.TH "words.cpp" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
words.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'words.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBWords\fP \fBwords\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBWords\fP \fBwords\fP"
.PP
Definition at line 80 of file words.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
