.TH "words.hpp" 3 "26 Nov 2012" "Word Prediction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
words.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWords\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBWords\fP \fBwords\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBWords\fP \fBwords\fP"
.PP
Definition at line 80 of file words.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Word Prediction from the source code.
